"""initial migration

Revision ID: a15003ec9054
Revises: 
Create Date: 2021-08-09 20:53:55.683561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15003ec9054'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.CheckConstraint('humidity >= 0 AND humidity <= 100', name=op.f('ck_records_humidity')),
    sa.CheckConstraint('temperature >= -100 AND temperature <= 100', name=op.f('ck_records_temperature')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_records'))
    )
    op.create_index(op.f('ix_records_timestamp'), 'records', ['timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_timestamp'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
